
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    volumes:
      - kafka-data:/var/lib/kafka/data

  flink-jobmanager:
    image: flink:1.18.1-scala_2.12-java11
    container_name: flink-jobmanager
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-jobmanager
    volumes:
      - ./flink-job:/opt/flink-job

  flink-taskmanager:
    image: flink:1.18.1-scala_2.12-java11
    container_name: flink-taskmanager
    depends_on:
      - flink-jobmanager
    command: taskmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-jobmanager
        taskmanager.numberOfTaskSlots: 2
        taskmanager.memory.process.size: 1024m
    volumes:
      - ./flink-job:/opt/flink-job

  hive-metastore-db:
    image: postgres:13
    container_name: hive-metastore-db
    environment:
      POSTGRES_USER: hive
      POSTGRES_PASSWORD: hive
      POSTGRES_DB: metastore
    ports:
      - "5432:5432"
    volumes:
      - hive-metastore-db-data:/var/lib/postgresql/data

  hive-metastore:
      image: apache/hive:4.0.0
      container_name: hive-metastore
      depends_on:
        - hive-metastore-db
      ports:
        - "9083:9083"
      environment:
        SERVICE_NAME: metastore
        DB_DRIVER: postgres
        SERVICE_OPTS: >-
          -Djavax.jdo.option.ConnectionDriverName=org.postgresql.Driver
          -Djavax.jdo.option.ConnectionURL=jdbc:postgresql://hive-metastore-db:5432/metastore
          -Djavax.jdo.option.ConnectionUserName=hive
          -Djavax.jdo.option.ConnectionPassword=hive
      volumes:
        - hive-warehouse:/opt/hive/data/warehouse
        - ./hive-config/postgresql-42.7.3.jar:/opt/hive/lib/postgresql-42.7.3.jar
        - ./data/hive-warehouse:/Users/shivank/Projects/fraud-lambda/data/hive-warehouse

      mem_limit: 1g

volumes:
  hive-metastore-db-data:
  kafka-data:
  hive-warehouse: